name: notes_app
description: Flutter application for making notes and learning technology.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ./domain
  data:
    path: ./data
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
