name: domain
description: A new Flutter package project.
version: 0.0.1
author: asdfv

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^0.6.0
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
